services:
  frontend:
    build: frontend
    ports:
      - '8080:5173'
    develop:
      watch:
        - action: sync
          path: frontend
          target: /app
  backend:
    build: backend
    ports:
      - '8080:3000'
    develop:
      watch:
        - action: sync
          path: backend
          target: /app
