services:
  redis:
    image: redis:latest
  frontend:
    build:
      context: .
      dockerfile: ./frontend.Dockerfile
    ports:
      - '8081:8080'
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      VUE_APP_BACKEND_URL: http://backend:3000
    develop:
      watch:
        - action: sync
          path: frontend
          target: /app
  backend:
    build:
      context: .
      dockerfile: ./backend.Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - redis
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
    develop:
      watch:
        - action: sync
          path: backend
          target: /app
