services:
  redis:
    image: redis:latest
  frontend:
    build:
      context: .
      dockerfile: ./frontend.Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - backend
    env_file:
      - path: ./default.env
        required: true # default
      - path: ./production.env
        required: false
    develop:
      watch:
        - action: sync
          path: frontend
          target: /app
  backend:
    build:
      context: .
      dockerfile: ./backend.Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - redis
    env_file:
      - path: ./default.env
        required: true # default
      - path: ./production.env
        required: false
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    develop:
      watch:
        - action: sync
          path: backend
          target: /app
